name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout tx-chain
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup SSH agent to access private repositories
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.TX_CRUST_PRIVATE_KEY }}
            ${{ secrets.TX_TOOLS_PRIVATE_KEY }}
            ${{ secrets.TX_WASM_SDK_PRIVATE_KEY }}
            ${{ secrets.TX_STD_DERIVE_PRIVATE_KEY }}
      - name: Setup access to private repositories
        run: |
          export GOPRIVATE=github.com/tokenize-x GONOSUMDB=github.com/tokenize-x
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          echo -e "${{ secrets.TX_CRUST_PRIVATE_KEY }}" > ~/.ssh/tx-crust-deploy-key
          echo -e "${{ secrets.TX_TOOLS_PRIVATE_KEY }}" > ~/.ssh/tx-tools-deploy-key
          echo -e "${{ secrets.TX_WASM_SDK_PRIVATE_KEY }}" > ~/.ssh/tx-wasm-sdk-deploy-key
          echo -e "${{ secrets.TX_STD_DERIVE_PRIVATE_KEY }}" > ~/.ssh/tx-std-derive-deploy-key
          chmod 600 ~/.ssh/tx-crust-deploy-key ~/.ssh/tx-tools-deploy-key ~/.ssh/tx-wasm-sdk-deploy-key ~/.ssh/tx-std-derive-deploy-key
          {
            echo -e "Host tx-crust-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-crust-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-tools-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-tools-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-wasm-sdk-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-wasm-sdk-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-std-derive-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-std-derive-deploy-key\n    IdentitiesOnly yes"
          } > ~/.ssh/config
          {
            echo -e "[url \"git@tx-crust-private:tokenize-x/tx-crust\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-crust\""
            echo -e "[url \"git@tx-tools-private:tokenize-x/tx-tools\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-tools\""
            echo -e "[url \"git@tx-wasm-sdk-private:tokenize-x/tx-wasm-sdk\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-wasm-sdk\""
            echo -e "[url \"git@tx-std-derive-private:tokenize-x/tx-std-derive\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-std-derive\""
          } > ~/.gitconfig
      - name: Build binaries
        run: make release
      - name: Build and publish images
        run: make release-images
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=release::true
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-rc.*$ ]]; then
              echo ::set-output name=release_candidate::true
          fi
      - name: Link released binaries under right names
        run: |
          ln bin/.cache/txd/docker.linux.amd64/bin/txd txd-linux-amd64
          ln bin/.cache/txd/docker.linux.arm64/bin/txd txd-linux-arm64
          ln bin/.cache/txd/docker.darwin.amd64/bin/txd txd-darwin-amd64
          ln bin/.cache/txd/docker.darwin.arm64/bin/txd txd-darwin-arm64
          sha256sum txd-* > checksums.txt
      - name: Create release
        if: steps.check-tag.outputs.release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            txd-linux-amd64
            txd-linux-arm64
            txd-darwin-amd64
            txd-darwin-arm64
            checksums.txt
      - name: Create release candidate
        if: steps.check-tag.outputs.release_candidate == 'true'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            txd-linux-amd64
            txd-linux-arm64
            txd-darwin-amd64
            txd-darwin-arm64
            checksums.txt
